ALTER TABLE `user` 
ADD COLUMN `MAIL` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱' AFTER `AVATAR_URL`,
ADD COLUMN `REMARK` VARCHAR(255) NULL DEFAULT NULL COMMENT '签名备注' AFTER `MAIL`,
ADD COLUMN `SOCIAL` VARCHAR(100) NULL DEFAULT NULL COMMENT '社交方式' AFTER `REMARK`;
